version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_rental_db
      MYSQL_USER: group9
      MYSQL_PASSWORD: group9
    ports:
      - "5050:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
